# 01 — Dataset Understanding

## Part A — Initial Dataset Analysis

This notebook performs the initial understanding and analysis of the datasets used in the **FraudLens-AI** project.

### Datasets Used

1. `HI-Small_accounts.csv`
2. `HI-Small_Trans_Custom.csv`

### Objectives

- Understand the structure and size of the datasets
- Analyze attributes and data types
- Identify missing and duplicate records
- Understand the relationship between accounts and transactions
- Analyze the connectivity of the transaction network
- Establish a clear understanding of the raw data before data cleaning and feature engineering

In [1]:
import pandas as pd
import os

In [9]:
accounts_path = r"D:\Projects\major project\FraudLens-AI\Data\Raw_Data\HI-Small_accounts.csv"
transactions_path = r"D:\Projects\major project\FraudLens-AI\Data\Raw_Data\HI-Small_Trans_Custom.csv"

In [10]:
accounts = pd.read_csv(accounts_path)
transactions = pd.read_csv(transactions_path)

In [11]:
print("Accounts dataset loaded:", accounts.shape)
print("Transactions dataset loaded:", transactions.shape)

Accounts dataset loaded: (518581, 5)
Transactions dataset loaded: (2505191, 11)

In [12]:
print("===== DATASET SIZE =====")

print(f"Accounts Rows      : {accounts.shape[0]:,}")
print(f"Accounts Columns   : {accounts.shape[1]:,}")

print(f"Transaction Rows   : {transactions.shape[0]:,}")
print(f"Transaction Columns: {transactions.shape[1]:,}")

===== DATASET SIZE =====
Accounts Rows      : 518,581
Accounts Columns   : 5
Transaction Rows   : 2,505,191
Transaction Columns: 11

In [6]:
def get_file_size(file_path):
    size_bytes = os.path.getsize(file_path)
    
    if size_bytes < 1024**2:
        return f"{size_bytes / 1024:.2f} KB"
    elif size_bytes < 1024**3:
        return f"{size_bytes / 1024**2:.2f} MB"
    else:
        return f"{size_bytes / 1024**3:.2f} GB"


print("===== FILE SIZE =====")

print("Accounts dataset    :", get_file_size(accounts_path))
print("Transactions dataset:", get_file_size(transactions_path))

===== FILE SIZE =====
Accounts dataset    : 32.48 MB
Transactions dataset: 218.56 MB

In [7]:
accounts.head()

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name
0,Portugal Bank #4507,331579,80B779D80,80062E240,Sole Proprietorship #50438
1,Canada Bank #27,210,809D86900,800C998A0,Corporation #33520
2,UK Bank #33,21884,80812BE00,800C47F50,Partnership #35397
3,Germany Bank #4815,32742,81047F300,80096F0B0,Corporation #48813
4,National Bank of Harrisburg,127390,80BD8CF00,800FB8760,Corporation #889

In [8]:
transactions.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [9]:
print("===== ACCOUNTS ATTRIBUTES =====")

for i, column in enumerate(accounts.columns, start=1):
    print(f"{i}. {column}")

===== ACCOUNTS ATTRIBUTES =====
1. Bank Name
2. Bank ID
3. Account Number
4. Entity ID
5. Entity Name

In [10]:
print("===== TRANSACTION ATTRIBUTES =====")

for i, column in enumerate(transactions.columns, start=1):
    print(f"{i}. {column}")

===== TRANSACTION ATTRIBUTES =====
1. Timestamp
2. From Bank
3. Account
4. To Bank
5. Account.1
6. Amount Received
7. Receiving Currency
8. Amount Paid
9. Payment Currency
10. Payment Format
11. Is Laundering

In [11]:
accounts_summary = pd.DataFrame({
    "Attribute": accounts.columns,
    "Data Type": accounts.dtypes.astype(str).values,
    "Non-Null Count": accounts.notna().sum().values,
    "Missing Count": accounts.isna().sum().values,
    "Unique Values": accounts.nunique().values
})

accounts_summary

        Attribute Data Type  Non-Null Count  Missing Count  Unique Values
0       Bank Name       str          518581              0          20053
1         Bank ID     int64          518581              0          30470
2  Account Number       str          518581              0         518573
3       Entity ID       str          518581              0         166207
4     Entity Name       str          518581              0         166207

In [12]:
transactions_summary = pd.DataFrame({
    "Attribute": transactions.columns,
    "Data Type": transactions.dtypes.astype(str).values,
    "Non-Null Count": transactions.notna().sum().values,
    "Missing Count": transactions.isna().sum().values,
    "Unique Values": transactions.nunique().values
})

transactions_summary

             Attribute Data Type  Non-Null Count  Missing Count  Unique Values
0            Timestamp       str         2505191              0          10642
1            From Bank     int64         2505191              0          30470
2              Account       str         2505191              0         491611
3              To Bank     int64         2505191              0          15811
4            Account.1       str         2505191              0         419428
5      Amount Received   float64         2505191              0         873414
6   Receiving Currency       str         2505191              0             15
7          Amount Paid   float64         2505191              0         881463
8     Payment Currency       str         2505191              0             15
9       Payment Format       str         2505191              0              7
10       Is Laundering     int64         2505191              0              2

In [13]:
print("===== ACCOUNTS DATA TYPES =====")
print(accounts.dtypes)

print("\n===== TRANSACTIONS DATA TYPES =====")
print(transactions.dtypes)

===== ACCOUNTS DATA TYPES =====
Bank Name           str
Bank ID           int64
Account Number      str
Entity ID           str
Entity Name         str
dtype: object

===== TRANSACTIONS DATA TYPES =====
Timestamp                 str
From Bank               int64
Account                   str
To Bank                 int64
Account.1                 str
Amount Received       float64
Receiving Currency        str
Amount Paid           float64
Payment Currency          str
Payment Format            str
Is Laundering           int64
dtype: object

In [14]:
accounts_missing = pd.DataFrame({
    "Attribute": accounts.columns,
    "Missing Count": accounts.isna().sum().values,
    "Missing Percentage": (
        accounts.isna().mean().values * 100
    ).round(2)
})

accounts_missing

        Attribute  Missing Count  Missing Percentage
0       Bank Name              0                 0.0
1         Bank ID              0                 0.0
2  Account Number              0                 0.0
3       Entity ID              0                 0.0
4     Entity Name              0                 0.0

In [15]:
transactions_missing = pd.DataFrame({
    "Attribute": transactions.columns,
    "Missing Count": transactions.isna().sum().values,
    "Missing Percentage": (
        transactions.isna().mean().values * 100
    ).round(2)
})

transactions_missing

             Attribute  Missing Count  Missing Percentage
0            Timestamp              0                 0.0
1            From Bank              0                 0.0
2              Account              0                 0.0
3              To Bank              0                 0.0
4            Account.1              0                 0.0
5      Amount Received              0                 0.0
6   Receiving Currency              0                 0.0
7          Amount Paid              0                 0.0
8     Payment Currency              0                 0.0
9       Payment Format              0                 0.0
10       Is Laundering              0                 0.0

In [16]:
account_duplicates = accounts.duplicated().sum()

print("Duplicate account records:", account_duplicates)

Duplicate account records: 0

In [17]:
transaction_duplicates = transactions.duplicated().sum()

print("Duplicate transaction records:", transaction_duplicates)

Duplicate transaction records: 0

In [18]:
print(transactions.columns.tolist())
print(accounts.columns.tolist())

['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1', 'Amount Received', 'Receiving Currency', 'Amount Paid', 'Payment Currency', 'Payment Format', 'Is Laundering']
['Bank Name', 'Bank ID', 'Account Number', 'Entity ID', 'Entity Name']

In [19]:
print("Unique Sender Accounts:",
      transactions["Account"].nunique())

print("Unique Receiver Accounts:",
      transactions["Account.1"].nunique())

Unique Sender Accounts: 491611
Unique Receiver Accounts: 419428

In [20]:
sender_accounts = set(transactions["Account"].dropna().unique())
receiver_accounts = set(transactions["Account.1"].dropna().unique())

transaction_accounts = sender_accounts.union(receiver_accounts)

print("Total Unique Accounts in Transactions:",
      len(transaction_accounts))

Total Unique Accounts in Transactions: 511984

In [21]:
for column in accounts.columns:
    print(
        column,
        "→",
        accounts[column].nunique(),
        "unique values"
    )

Bank Name → 20053 unique values
Bank ID → 30470 unique values
Account Number → 518573 unique values
Entity ID → 166207 unique values
Entity Name → 166207 unique values

In [25]:
account_master_set = set(
    accounts["Account Number"].dropna().unique()
)

print("Unique accounts in Accounts dataset:",
      len(account_master_set))

Unique accounts in Accounts dataset: 518573

In [26]:
sender_not_found = (
    sender_accounts - account_master_set
)

receiver_not_found = (
    receiver_accounts - account_master_set
)

print("Sender accounts not found:",
      len(sender_not_found))

print("Receiver accounts not found:",
      len(receiver_not_found))

Sender accounts not found: 0
Receiver accounts not found: 0

In [27]:
print("===== GRAPH CONNECTIVITY =====")

print("Unique Sender Accounts  :", len(sender_accounts))
print("Unique Receiver Accounts:", len(receiver_accounts))
print("Total Unique Accounts   :", len(transaction_accounts))
print("Total Transactions      :", len(transactions))

===== GRAPH CONNECTIVITY =====
Unique Sender Accounts  : 491611
Unique Receiver Accounts: 419428
Total Unique Accounts   : 511984
Total Transactions      : 2505191

In [28]:
part_a_summary = pd.DataFrame({
    "Metric": [
        "Accounts Rows",
        "Accounts Columns",
        "Transaction Rows",
        "Transaction Columns",
        "Account Duplicates",
        "Transaction Duplicates",
        "Unique Transaction Accounts"
    ],
    "Value": [
        accounts.shape[0],
        accounts.shape[1],
        transactions.shape[0],
        transactions.shape[1],
        accounts.duplicated().sum(),
        transactions.duplicated().sum(),
        len(transaction_accounts)
    ]
})

part_a_summary

                        Metric    Value
0                Accounts Rows   518581
1             Accounts Columns        5
2             Transaction Rows  2505191
3          Transaction Columns       11
4           Account Duplicates        0
5       Transaction Duplicates        0
6  Unique Transaction Accounts   511984

## Part A — Dataset Understanding Summary

### Datasets Used

1. `HI-Small_accounts.csv`
2. `HI-Small_Trans_Custom.csv`

### Findings

- The accounts dataset provides account-level information.
- The transaction dataset contains relationships between sender and receiver accounts.
- The transaction data can be represented as a directed graph.
- Accounts will be represented as graph nodes.
- Transactions will be represented as graph edges.
- The original transaction fields `Account` and `Account.1` will later be represented in the database as `Sender_Account` and `Receiver_Account`.
- The exact relationship between the two datasets must be validated before database creation.

### Part A Status

Dataset understanding completed.

### Next Part

**Part B — Data Cleaning**